[project]
name = "cortexa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Vaibhav Thakur", email = "vaibhavt459@gmail.com"},
    {name = "Anirban Sharma", email = "anirbansharma007@gmail.com"},
]
license = {text = "MIT"}
dependencies = [
    "ipykernel",
    "ipywidgets",
    "langchain",
    "langchain-community",
    "langchain-core",
    "matplotlib",
    "numpy",
    "omegaconf>=2.3.0",
    "pandas",
    "paperscraper>=0.2.15",
    "pathlib2",
    "polars>=1.23.0",
    "python-dotenv",
    "scikit-learn",
    "scipy",
    "seaborn",
    "transformers",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
